apiVersion: v1
kind: Pod
metadata:
  name: mypod1
spec:
  volumes:
    - name: mypd
      hostPath:
          path: /mnt/usr/share/nginx/html
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: mypd
      ports:
       - containerPort: 80
         protocol: TCP
